const items = window.FINIF_EXPERIMENT3_ITEMS || [];
const batchId = 'finif-experiment3-qwen35-27b-20261006-v1';
let current = 0;
let annotator = localStorage.getItem('finif_e3_annotator') || 'A1';
const $ = id => document.getElementById(id);
$('annotatorSelect').value = annotator;
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const key = (itemId, slot) => `finif_${batchId}_${annotator}_${itemId}_${slot}`;
function blank(item, c) { return { review_batch_id:batchId, annotator_id:annotator, sample_no:item.sample_no, sample_id:c.sample_id, item_id:item.item_id, workflow:item.workflow, response_model:item.response_model, constraint_slot:c.constraint_slot, constraint_index:c.constraint_index, constraint:c.constraint, human_verdict:'', human_reason:'', updated_at:'' }; }
function getRecord(item,c) { try { return {...blank(item,c),...JSON.parse(localStorage.getItem(key(item.item_id,c.constraint_slot)) || '{}')}; } catch { return blank(item,c); } }
function saveRecord(item,c,record) { record.updated_at=new Date().toISOString(); record.annotator_id=annotator; localStorage.setItem(key(item.item_id,c.constraint_slot),JSON.stringify(record)); renderList(); updateProgress(); }
function itemComplete(item) { return item.constraints.every(c => ['pass','fail'].includes(getRecord(item,c).human_verdict)); }
function renderList() { $('itemList').innerHTML=items.map((item,i)=>`<button class="item-chip ${i===current?'active':''} ${itemComplete(item)?'complete':''}" data-i="${i}"><span class="chip-no">${item.sample_no}. ${escapeHtml(item.item_id)}</span><span class="chip-title">${escapeHtml(item.workflow)}</span></button>`).join(''); document.querySelectorAll('.item-chip').forEach(b=>b.onclick=()=>{current=Number(b.dataset.i);render();}); }
function updateProgress() { const total=items.reduce((n,x)=>n+x.constraints.length,0); const done=items.reduce((n,x)=>n+x.constraints.filter(c=>['pass','fail'].includes(getRecord(x,c).human_verdict)).length,0); $('progressText').textContent=`${done} / ${total} constraints`; $('progressBar').style.width=`${total?done/total*100:0}%`; }
function renderMeta(item) { $('metaGrid').innerHTML=[['Workflow',item.workflow],['Item ID',item.item_id],['Response model',item.response_model]].map(([a,b])=>`<div class="meta"><span>${a}</span><strong>${escapeHtml(b)}</strong></div>`).join(''); }
function renderConstraints(item) { $('constraintForms').innerHTML=item.constraints.map(c=>{ const r=getRecord(item,c); return `<section class="constraint-form" data-slot="${c.constraint_slot}"><div class="constraint-title"><span>Constraint ${c.constraint_slot}</span><span class="badge">原编号 ${c.constraint_index}</span></div><p class="constraint-text">${escapeHtml(c.constraint)}</p><div class="choice-buttons"><button type="button" data-verdict="pass" class="${r.human_verdict==='pass'?'selected-pass':''}">Pass</button><button type="button" data-verdict="fail" class="${r.human_verdict==='fail'?'selected-fail':''}">Fail</button></div><label class="reason-label">判断理由（建议填写，Fail 时请填写）</label><textarea class="reason" rows="2" placeholder="简要说明回复中支持判定的证据或缺失点">${escapeHtml(r.human_reason)}</textarea></section>`; }).join(''); document.querySelectorAll('.constraint-form').forEach(section=>{ const c=item.constraints.find(x=>x.constraint_slot===Number(section.dataset.slot)); section.querySelectorAll('[data-verdict]').forEach(button=>button.onclick=()=>{const r=getRecord(item,c);r.human_verdict=button.dataset.verdict;saveRecord(item,c,r);renderConstraints(item);}); section.querySelector('.reason').oninput=e=>{const r=getRecord(item,c);r.human_reason=e.target.value;saveRecord(item,c,r);}; }); }
function render() { const item=items[current]; if(!item)return; $('itemCounter').textContent=`${current+1} / ${items.length}`; $('jumpInput').value=current+1; renderMeta(item); $('fullPromptText').textContent=item.full_prompt; $('responseText').textContent=item.response; renderConstraints(item); renderList(); updateProgress(); }
$('prevBtn').onclick=()=>{current=Math.max(0,current-1);render();}; $('nextBtn').onclick=()=>{current=Math.min(items.length-1,current+1);render();};
$('jumpForm').onsubmit=e=>{e.preventDefault();const n=Number($('jumpInput').value);if(Number.isInteger(n)&&n>=1&&n<=items.length){current=n-1;render();}};
$('annotatorSelect').onchange=e=>{annotator=e.target.value;localStorage.setItem('finif_e3_annotator',annotator);render();};
$('copyPromptBtn').onclick=async()=>{try{await navigator.clipboard.writeText(items[current].full_prompt);$('copyPromptStatus').textContent='已复制';}catch{$('copyPromptStatus').textContent='复制失败，请手动复制';}};
function csvCell(v){return `"${String(v??'').replace(/"/g,'""')}"`;}
$('downloadBtn').onclick=()=>{const header=['review_batch_id','annotator_id','sample_no','sample_id','item_id','workflow','response_model','constraint_slot','constraint_index','constraint','human_verdict','human_reason','updated_at'];const lines=[header.join(',')];items.forEach(item=>item.constraints.forEach(c=>{const r=getRecord(item,c);lines.push(header.map(k=>csvCell(r[k])).join(','));}));const blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`finif_experiment3_human_${annotator}.csv`;a.click();URL.revokeObjectURL(url);};
render();
